services:
  # Streamlit Application
  streamlit-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: vector-db-embeddings:v1.0.3
    container_name: vector-db-embeddings
    ports:
      - "5260:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - QDRANT_HOST=host.docker.internal  # Connect to host's Qdrant
      - QDRANT_PORT=6333
    volumes:
      - ./models:/app/models:ro  # Read-only model files
      - ./config:/app/config:ro  # Configuration files
      - app_data:/app/data  # Persistent storage for user settings
    restart: unless-stopped

# Named volumes for persistent data
volumes:
  app_data:
    driver: local